export const GET_LAST_SEARCHED_DEFINITION = 'GET_LAST_SEARCHED_DEFINITION';
export const GET_LAST_VERB_CONJUAGATED = 'GET_LAST_VERB_CONJUAGATED';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';